log: 'debug'
logger: 'file'
startup_info: 1
show_errors:  1
port: 2080
template: template_toolkit
session: YAML
layout: main
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
